-- ==========================================
-- Supabase 資料表初始化腳本: processed_articles
-- 說明: 用於儲存已推播的新聞與文章雜湊值，防止重複推播，並支援週末週報溯源總結
-- ==========================================

CREATE TABLE IF NOT EXISTS processed_articles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url_hash VARCHAR(64) NOT NULL UNIQUE,
    title TEXT NOT NULL,
    source VARCHAR(64) NOT NULL,
    published_at TIMESTAMPTZ,
    category VARCHAR(32) DEFAULT 'general',
    summary_markdown TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 建立 URL 雜湊值索引以加速去重比對
CREATE INDEX IF NOT EXISTS idx_processed_articles_hash ON processed_articles(url_hash);

-- 建立建立時間索引以加速定時清理與近 7 天週報查詢
CREATE INDEX IF NOT EXISTS idx_processed_articles_created_at ON processed_articles(created_at);

-- 啟用行級安全性 (Row Level Security)，並允許服務端憑證存取
ALTER TABLE processed_articles ENABLE ROW LEVEL SECURITY;

-- 允許已認證的服務端密鑰 (service_role 或 anon 讀寫)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'processed_articles' AND policyname = 'Allow service_role full access'
    ) THEN
        CREATE POLICY "Allow service_role full access" ON processed_articles
            FOR ALL
            TO authenticated, anon, service_role
            USING (true)
            WITH CHECK (true);
    END IF;
END
$$;
